### ISSUE TITLE
Can't push data

### ISSUE THREAD

**Issue by Kuzmin-Dmitry** [the-maux/tipboard#85]
Config:
```
details:
    page_title: Tipboard
    color_mode: white
layout:
    - row_1_of_1:
        - col_1_of_1:
            - tile_template: text
              tile_id: text
              title: Just text
              details:
```
Redis 4 db: `1) "tipboard-python3:tile:text"`

Request:
```
curl http://localhost:8080/api/push \
     -X POST \
     -d "tile=text" \
     -d "key=text" \
     -d 'data={"text": "Hello world!"}'
```
Response:
```
Bad Request: /api/push
HTTP POST /api/push 400 [0.01, 127.0.0.1:42344]
Missing data
```
I tried to add api version or/and api key and just get 404 response
Please tell me right way to push data
